
CREATE TABLE GROUP_TABLE(
   GROUP_ID INT PRIMARY KEY      NOT NULL,
   GROUP_TITLE CHAR(50)			 NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USER_TABLE(USER_ID)
);

CREATE TABLE USER_TABLE(
   USER_ID INT PRIMARY KEY      NOT NULL,
   USER_NAME CHAR(50)			NOT NULL,
   PASSWORD  CHAR(50)			NOT NULL,
   FIRST_NAME CHAR(50)			NOT NULL,
   EMAIL CHAR(50)				NOT NULL,
   PHONE_NUMBER INT(50)			NOT NULL,
		FOREIGN KEY (GROUP_ID) REFERENCES GROUP_TABLE(GROUP_ID),
		FOREIGN KEY (CHORES_TITLE) REFERENCES CHROES_TABLE(CHORES_TITLE)
);

CREATE TABLE CHORES_TABLE(
   CHORES_TITLE INT PRIMARY KEY     NOT NULL,
   COMP_BY_DATE DATE				NOT NULL,
   COMPLETED_BY  DATE				NOT NULL,
   COMPLETED_DATE DATE				NOT NULL,
   CHORE_ID CHAR(50)				NOT NULL,
   CHORE_PRIORTY INT				NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USER_TABLE(USER_ID)
);















